title: Théo Berthet

theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

# Enable this for sidebar navigation
minimal_mistakes_skin: "default"

# Navigation structure
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
        
# Site author info (shown in sidebar/profile)
author:
  name: Your Name
  avatar: "/assets/images/profile.jpg"
  bio: "Short 1-line bio here."
  location: Paris, France
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourusername"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
