title: Théo Berthet

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Minimal Mistakes skin (color theme)
minimal_mistakes_skin: "default"

# Sidebar author profile
author:
  name: Your Name
  avatar: "/assets/images/profile.jpg"
  bio: "Short one-liner about you"
  location: "France"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourname"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourhandle"

# Navigation sidebar
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
