title: Théo Berthet

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Minimal Mistakes skin (color theme)
minimal_mistakes_skin: "default"

# Sidebar author profile
author:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "berthettheopg@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/th%C3%A9o-berthet-91a5a024b/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/TBerthet/"


# Navigation sidebar
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
